### PR TITLE
added edit_usergroup()

### PR DESCRIPTION
**Pull request by afarrapeira**
Hi, I added a few new functions regading usergroups:

- edit_usergroup() allows people to edit the usergroup's name and its upload and download bandwith limits.

- add_usergroup()

- delete_usergroup() 

I also had to edit the exec_curl function to add the 'DELETE' HTTP method.

### CODE REVIEW

**Comment by malle-pietje** [comment]
@afarrapeira Thanks for the contribution! I'll have a look at it before I merge it in but at first glance the code looks nice and clean. BTW, I had not yet seen that the API is gradually moving more towards a true REST API by adding the DELETE command. Interesting:)

Also, have you tried whether we can do a more strict comparison using `===` in `exec_curl` when testing for PUT or DELETE? Would just be a bit cleaner I think. I haven't taken the time for that yet...

**Comment by malle-pietje** [comment]
@afarrapeira One more question: is the effect of the default value `-1` for the speeds that the respective speed limit is disabled, so unlimited?

**Comment by afarrapeira** [comment]
@malle-pietje I haven't tried the strict comparison in `exec_curl` yet, sorry :(

Yes, `-1` is the value the controller uses for an unlimited bandwidth, that's why I used it as the default value.

Also, I noticed I should have used brackets in `edit_usergroup` instead of `array()`

**Comment by malle-pietje** [comment]
OK, that's clear! I'll modify the brackets (just for consistency) and also see whether I can add a comment regarding the default value.

**Comment by afarrapeira** [comment]
Awesome, thanks! :grin:

**Comment by malle-pietje** [comment]
Done! Thanks for your help:)

**Pull request merged**
